### ISSUE TITLE
Not getting any results

### ISSUE THREAD

**Issue by EduardoRT** [wincent/vcs-jump#1]
Hi!

I'm not getting anything in my quickfix list after doing any of the VcsJump commands, `:VcsJump diff`, `:VcsJump merge` and `:VcsJump grep` - I do have ruby in my path and there's no error, I've tried with different git options like `--cached` and my staged changes don't appear either, I'm using [Plug](https://github.com/junegunn/vim-plug) as my package manager and I'm on neovim 4.0.

Thanks!

**Comment by wincent** [comment]
@EduardoRT: Can you try running the `vcs-jump` executable from the command-line directly, outside of Vim, and see what it does?

For example, if you installed in `~/.vim/pack/bundle/opt/vcs-jump`, it would be at `~/.vim/pack/bundle/opt/vcs-jump/bin/vcs-jump`. Here's an example from a repo where I am now:

```sh
# Opens Vim with the changed files:
~/.vim/pack/bundle/opt/vcs-jump/bin/vcs-jump diff

# Instead of opening Vim, print the arguments that would be passed to Vim:
env EDITOR=/bin/echo ~/.vim/pack/bundle/opt/vcs-jump/bin/vcs-jump diff
-q /var/folders/yc/1x2y2qld1g95tvtjpd89hdrm0000gp/T/vcs-jump20190610-46050-hopk62

# Look inside the temporarily file that was echoed above to see which files Vim should open:
cat /var/folders/yc/1x2y2qld1g95tvtjpd89hdrm0000gp/T/vcs-jump20190610-46050-hopk62
apps/frontend-js/frontend-js-web/src/main/resources/META-INF/resources/liferay/side_navigation.es.js:232:
apps/frontend-js/frontend-js-web/src/main/resources/META-INF/resources/liferay/side_navigation.es.js:784: console.log('maybe subscribing', this.options.container);
apps/frontend-taglib/frontend-taglib-clay/src/main/resources/META-INF/resources/management_toolbar/ManagementToolbar.es.js:203: console.log('row toggled');
```

**Comment by EduardoRT** [comment]
Running the executable directly from the command line opens vim with an status of `E42: No Errors`.

![image](https://user-images.githubusercontent.com/1114422/59210336-f8e80a80-8b72-11e9-82ec-e98074482c2b.png)

I can't get the second command to echo the tmp folders, it just opens neovim again with the same status - I'm on Ubuntu 18.10 if that helps.

**Comment by wincent** [comment]
I can't see how it would open Neovim if you have your `EDITOR` set to `/bin/echo`...

Try something else: what does `git diff --relative` print? (That's the command that vcs-jump is using to get the list of changes.)

**Comment by EduardoRT** [comment]
`git diff --relative` gets me a correct diff (deleted random lines from one repo)

![image](https://user-images.githubusercontent.com/1114422/59211110-af98ba80-8b74-11e9-8a36-98bb832b72fb.png)

I've changed both `VISUAL` and `EDITOR` and when doing `<C-x-e>` it echos it out to a tmp file correctly but when running the vcs-jump command it still opens neovim.

![image](https://user-images.githubusercontent.com/1114422/59211522-a3f9c380-8b75-11e9-987d-fb98da5aecb3.png)

**Comment by wincent** [comment]
Ah, I forgot... it will use `GIT_EDITOR` preferentially before `EDITOR`, so I think setting `GIT_EDITOR=/bin/echo` will do the trick.

If it doesn't you could just edit the script to make it print out what arguments it is going to pass to Vim:

```
diff --git a/bin/vcs-jump b/bin/vcs-jump
index 28c2c6b..cdd589f 100755
--- a/bin/vcs-jump
+++ b/bin/vcs-jump
@@ -35,7 +35,8 @@ def open_editor(tmp)
     additional_args = %w[-c :cw] # open the quickfix window
   end
 
-  exec(editor, '-q', tmp, *additional_args)
+  p editor, tmp, additional_args
+  # exec(editor, '-q', tmp, *additional_args)
 end
 
 def pwd
```

My guess here is that it's probably printing the right thing, so there must be some explanation for why your Neovim isn't doing the desired thing.

**Comment by EduardoRT** [comment]
That did the trick, the tmp file is empty though

![image](https://user-images.githubusercontent.com/1114422/59215820-dad4d700-8b7f-11e9-87a4-3c836af26c78.png)

**Comment by EduardoRT** [comment]
Weirdly enough, the `:VcsJump merge` command works as intended.

**Comment by wincent** [comment]
I wonder, are you in a subdirectory — not the project root — when you run it?

**Comment by EduardoRT** [comment]
I am in the project root when running it :/

**Comment by wincent** [comment]
Well it's pretty odd that the file is empty. You can also try running it like this:

```sh
path/tobin/vcs-jump diff | cat
```

That should force it to print rather than write to a file.

**Comment by EduardoRT** [comment]
Nada

![image](https://user-images.githubusercontent.com/1114422/59220186-fa70fd00-8b89-11e9-8ccf-c4d20905af1f.png)

**Comment by wincent** [comment]
At this point I don't know what to suggest other than adding some logging statements to see what the heck is going on.

```diff
diff --git a/bin/vcs-jump b/bin/vcs-jump
index 28c2c6b..4304625 100755
--- a/bin/vcs-jump
+++ b/bin/vcs-jump
@@ -103,7 +103,9 @@ end
 
 def mode_diff(args)
   args = shellescape(args)
+  puts "git? #{git?}"
   diff =  git? ? `git diff --relative #{args}` : `hg diff --git --root . #{args}`
+  puts diff
   idx  = nil
   file = nil
 
@@ -162,6 +164,8 @@ if STDOUT.tty?
   ensure
     tmp.close
   end
+
 else
+  puts "running: #{mode}"
   send("mode_#{mode}", ARGV)
 end
```

etc. If that doesn't reveal what's going on, add more logging statements.

**Comment by EduardoRT** [comment]
Odd, when adding those statements I do get the expected diff

![image](https://user-images.githubusercontent.com/1114422/59232677-0ae59f80-8bab-11e9-82f0-e5e1f3666f7a.png)

**Comment by wincent** [comment]
Weird, so the `puts` statement that dumps the diff printed it in color? That makes me wonder if you have something like `git config color.ui` set to "always" instead of auto... You could test that theory out by running: `:VcsJump diff --color=never`.

**Comment by EduardoRT** [comment]
That was it! I did have the color config set to always, changing it to auto fixed the issue, maybe it's a good idea to add the `--color=never` flag to the `VcsJump` call?

Thanks @wincent ! The project is awesome :)

**Comment by wincent** [comment]
Yeah, I think adding `--color=never` is a good idea, and hopefully safe (I don't know exactly when it was added to Git, but it is probably ancient history by now).
